var annotated_dup =
[
    [ "_$Address", "class___0bAddress.html", null ],
    [ "_$CourseOfStudy", "class___0bCourseOfStudy.html", null ],
    [ "_$ErrorsResponse", "class___0bErrorsResponse.html", null ],
    [ "_$Faculty", "class___0bFaculty.html", null ],
    [ "_$Lecture", "class___0bLecture.html", null ],
    [ "_$PhoneNumber", "class___0bPhoneNumber.html", null ],
    [ "_$Schedule", "class___0bSchedule.html", null ],
    [ "_$Student", "class___0bStudent.html", null ],
    [ "_$StudentLoginResponse", "class___0bStudentLoginResponse.html", null ],
    [ "_$StudentLoginWithUsernameAndPasswordData", "class___0bStudentLoginWithUsernameAndPasswordData.html", null ],
    [ "_$WeekPartTimeSchedule", "class___0bWeekPartTimeSchedule.html", null ],
    [ "ConsumerStatefulWidget", "classConsumerStatefulWidget.html", null ],
    [ "ConsumerWidget", "classConsumerWidget.html", null ],
    [ "CustomInputBorders", "classCustomInputBorders.html", null ],
    [ "DefaultFirebaseOptions", "classDefaultFirebaseOptions.html", null ],
    [ "Event", "classEvent.html", null ],
    [ "Exception", "classException.html", null ],
    [ "FirebaseApi", "classFirebaseApi.html", null ],
    [ "ImagePickerService", "classImagePickerService.html", null ],
    [ "StatefulWidget", "classStatefulWidget.html", null ],
    [ "StatelessWidget", "classStatelessWidget.html", null ],
    [ "StateNotifier< bool >", "classStateNotifier_3_01bool_01_4.html", null ],
    [ "StateNotifier< Locale >", "classStateNotifier_3_01Locale_01_4.html", null ],
    [ "StateNotifier< String >", "classStateNotifier_3_01String_01_4.html", null ],
    [ "WirtualnyAuth", "classWirtualnyAuth.html", null ],
    [ "WirtualnyHttpClient", "classWirtualnyHttpClient.html", null ],
    [ "WirtualnySdk", "classWirtualnySdk.html", null ],
    [ "WirtualnySdkConfig", "classWirtualnySdkConfig.html", null ]
];