var annotated_dup =
[
    [ "Address", "classAddress.html", null ],
    [ "AppUser", "classAppUser.html", null ],
    [ "AuthService", "classAuthService.html", null ],
    [ "BaseClient", "classBaseClient.html", null ],
    [ "ConsumerStatefulWidget", "classConsumerStatefulWidget.html", null ],
    [ "ConsumerWidget", "classConsumerWidget.html", null ],
    [ "CoursesOfStudy", "classCoursesOfStudy.html", null ],
    [ "CustomInputBorders", "classCustomInputBorders.html", null ],
    [ "DefaultFirebaseOptions", "classDefaultFirebaseOptions.html", null ],
    [ "Event", "classEvent.html", null ],
    [ "Faculty", "classFaculty.html", null ],
    [ "FirebaseApi", "classFirebaseApi.html", null ],
    [ "ImagePickerService", "classImagePickerService.html", null ],
    [ "Lecture", "classLecture.html", null ],
    [ "PhoneNumber", "classPhoneNumber.html", null ],
    [ "StatefulWidget", "classStatefulWidget.html", null ],
    [ "StatelessWidget", "classStatelessWidget.html", null ],
    [ "StateNotifier< bool >", "classStateNotifier_3_01bool_01_4.html", null ],
    [ "StateNotifier< Locale >", "classStateNotifier_3_01Locale_01_4.html", null ],
    [ "StateNotifier< String >", "classStateNotifier_3_01String_01_4.html", null ],
    [ "Student", "classStudent.html", null ],
    [ "StudentLoginData", "classStudentLoginData.html", null ],
    [ "StudentLoginResponse", "classStudentLoginResponse.html", null ],
    [ "WeekPartTimeSchedule", "classWeekPartTimeSchedule.html", null ],
    [ "WirtualnySdk", "classWirtualnySdk.html", null ]
];