var NAVTREEINDEX0 =
{
"annotated.html":[1,0],
"classAppUser.html":[1,0,0],
"classAuthService.html":[1,0,1],
"classConsumerStatefulWidget.html":[1,0,2],
"classConsumerWidget.html":[1,0,3],
"classCustomInputBorders.html":[1,0,4],
"classDefaultFirebaseOptions.html":[1,0,5],
"classEvent.html":[1,0,6],
"classFirebaseApi.html":[1,0,7],
"classImagePickerService.html":[1,0,8],
"classStateNotifier_3_01Locale_01_4.html":[1,0,12],
"classStateNotifier_3_01bool_01_4.html":[1,0,11],
"classStatefulWidget.html":[1,0,9],
"classStatelessWidget.html":[1,0,10],
"classes.html":[1,1],
"index.html":[],
"md_README.html":[0],
"pages.html":[]
};
