name: Generate Doxygen documentation

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  generate-doxygen-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt update && sudo apt install -y graphviz

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Node dependencies
        run: npm install

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Doxygen Documentation without LaTeX
        uses: mattnotmitt/doxygen-action@edge

      - name: Generate Doxygen Documentation with LaTeX
        uses: mattnotmitt/doxygen-action@edge
        with:
          enable-latex: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doxygen/html
          # cname: gh-pages.mateuszbasiaga.pl

      - name: Prepare PDF file
        run: cp ./docs/doxygen/latex/refman.pdf ./doxygen-docs.pdf

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "doxygen-docs.pdf"
          allowUpdates: true
